/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/demo/demo.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IndexTs: typeof import('./src/components/form/input-divider/src/index-ts.vue')['default']
    IndexV1: typeof import('./src/components/form/input-number/src/indexV1.vue')['default']
    Src: typeof import('./src/components/countdown/src/index.vue')['default']
    TextareaDialog: typeof import('./src/components/form/input-expand/src/textareaDialog.vue')['default']
  }
}
